name: diffdrr
channels:
  - conda-forge
  - pytorch
  - pytorch3d
  - nvidia
dependencies:
  - pip
  - pytorch
  - pytorch3d
  - pydicom
  - matplotlib
  - seaborn
  - tqdm
  - imageio
  - fastcore
  - pip:
    - 'pyvista[all]'
