name: Docs

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Activate conda env with environment.yml
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          auto-activate-base: false
          activate-environment: gtbook
          python-version: 3.9
          environment-file: environment.yml

      - name: Install nbdev
        shell: bash -l {0}
        run: |
          pip install -U nbdev

      - name: Doing editable install
        shell: bash -l {0}
        run: |
          test -f setup.py && pip install -e ".[dev]"

      - name: Run nbdev_docs
        shell: bash -l {0}
        run: |
          nbdev_docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          force_orphan: true
          publish_dir: ./_docs
          # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
